[package]
name = "conch"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conch"
path = "src/main.rs"

[dependencies]
conch-core = { path = "../conch-core" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
